name: CI

on:
  push:
    branches: [ master ]
  # pull_request:
  #  branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Vscode plugin release action
        uses: JCofman/vscodeaction@v2.0.1
