name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: npm install
        uses: actions/npm@master
        with:
          args: install --unsafe-perm
      - name: Master
        uses: actions/bin/filter@master
        with:
          args: branch master
      - name: Vscode release plugin
        uses: JCofman/vscodeaction@master
        env:
          PUBLISHER_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          args: publish -p $PUBLISHER_TOKEN
